AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda SpringBoot 3.4 with Spring Cloud Function AWS Adapter
  Sample SAM Template 

Parameters:
  Stage:
    Type: String
    Default: prod
    
Globals:
  Function:
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    CodeUri: target/aws-lambda-spring-boot-3.4-spring-cloud-function-aws-1.0.0-SNAPSHOT.jar
    Runtime: java21
    SnapStart:
      ApplyOn: PublishedVersions   
    Timeout: 30 
    MemorySize: 1024   
    Environment:
      Variables:
        #JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
        MAIN_CLASS: software.amazonaws.Application
        PRODUCT_TABLE_NAME: !Ref ProductsTable

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    DependsOn: MyApiCWLRoleArn 
    Properties:
      StageName: !Ref Stage
      Name: AWSLambdaSpringBoot34SpringCloudFunctionAWSAPI
      Description: Product API using AWS Lambda with Spring Boot 3.4 and Spring Cloud Function AWS Adapter
      AccessLogSetting:
        DestinationArn: !Sub ${MyApiLogGroup.Arn} # This Log Group is already created within our SAM Template
        Format: "{'integrationLatency':'$context.integrationLatency', 'latency':'$context.responseLatency', 'requestId':'$context.requestId', 'ip': '$context.identity.sourceIp', 'caller':'$context.identity.caller', 'user':'$context.identity.user','requestTime':'$context.requestTime', 'xrayTraceId':'$context.xrayTraceId', 'wafResponseCode':'$context.wafResponseCode', 'httpMethod':'$context.httpMethod','resourcePath':'$context.resourcePath', 'status':'$context.status','protocol':'$context.protocol', 'responseLength':'$context.responseLength' }"
      #MethodSettings:
       # - MetricsEnabled: True
       #   ResourcePath: '/*'
       #   HttpMethod: '*'
      Auth:
        ApiKeyRequired: true  # sets for all methods


  MyApiCWLRoleArn:
   Type: AWS::ApiGateway::Account
   Properties: 
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn
      
  # IAM Role for API GW + CWL
  CloudWatchRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Path: /
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'         
        
  MyApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
       LogGroupName: !Sub "/aws/apigateway/${MyApi}"
       RetentionInDays: 7


  MyApiUsagePlan:
     Type: AWS::ApiGateway::UsagePlan
     DependsOn:  
        - MyApiStage
     Properties:
      ApiStages: 
        - ApiId: !Ref MyApi
          Stage: !Ref Stage
      UsagePlanName: AWSLambdaSpringBoot34SpringCloudFunctionAWSAPIUsagePlan
      Description: Usage plan for AWSLambdaSpringBoot34SpringCloudFunctionAWSAPIUsagePlan
      Quota:
          Limit: 2000000
          Period: DAY
      Throttle:
          RateLimit:  10000
          BurstLimit: 50000   

  MyApiKey: 
    Type: AWS::ApiGateway::ApiKey
    DependsOn:  
       - MyApiStage
    Properties: 
      Name: "AWSLambdaSpringBoot34SpringCloudFunctionAWSApiKey"
      Description: "AWSLambdaSpringBoot34SpringCloudFunctionAWS API Key"
      Enabled: true
      GenerateDistinctId: false
      Value: a6ZbcDefQW12BN56WEJ34
      StageKeys:
        - RestApiId: !Ref MyApi
          StageName: !Ref Stage

  MyApiUsagePlanKey:
      Type: "AWS::ApiGateway::UsagePlanKey"
      DependsOn: 
      - MyApi
      Properties:
        KeyId: !Ref MyApiKey
        KeyType: API_KEY
        UsagePlanId: !Ref MyApiUsagePlan

 
  GetProductByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
           SPRING_CLOUD_FUNCTION_DEFINITION: getProductByIdHandler
      FunctionName: GetProductByIdWithSpringBoot34WithSpringCloudFunctionAWS
      AutoPublishAlias: liveVersion
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /products/{id}
            Method: get            

  GetProductByIdFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetProductByIdFunction}"
      RetentionInDays: 7


  GetProductByIdWithDynamoDBRequestPrimingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
           SPRING_CLOUD_FUNCTION_DEFINITION: getProductByIdWithDynamoDBRequestPrimingHandler
      FunctionName: GetProductByIdWithSpringBoot34WithSpringCloudFunctionAWSDPriming
      AutoPublishAlias: liveVersion
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /productsWithDynamoDBPriming/{id}
            Method: get            

  GetProductByIdWithDynamoDBRequestPrimingFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetProductByIdWithDynamoDBRequestPrimingFunction}"
      RetentionInDays: 7
      
      
  GetProductByIdWithWebRequestPrimingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
           SPRING_CLOUD_FUNCTION_DEFINITION: getProductByIdWithWebRequestPrimingHandler
      FunctionName: GetProductByIdWithSpringBoot34WithSpringCloudFunctionAWSWPriming
      AutoPublishAlias: liveVersion
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /productsWithWebRequestPriming/{id}
            Method: get            

  GetProductByIdWithWebRequestPrimingFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetProductByIdWithWebRequestPrimingFunction}"
      RetentionInDays: 7
 

 
  PutProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: createProductHandler
      FunctionName: PutProductWithSpringBoot34WithSpringCloudFunctionAWS
      AutoPublishAlias: liveVersion
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        PutRequest:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /products
            Method: put

  PutProductFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PutProductFunction}"
      RetentionInDays: 7

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "AWSLambdaSpringBoot34WithSpringCloudFunctionAWSProductsTable"
      PointInTimeRecoverySpecification:
         PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: 'PK'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'PK'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST    
      #ProvisionedThroughput: 
        #ReadCapacityUnits: "1"
        #WriteCapacityUnits: "1"
      

Outputs:
  AWSLambdaSpringBoot34WithSpringCloudFunctionAWSApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for AWS Lambda Spring Boot 3.4 with Spring Cloud Function AWS Adapter"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/products"
