version = 0.1
[default.deploy.parameters]
stack_name = "AWSSpringBoot32LambdaWebAdapter"
resolve_s3 = true
s3_prefix = "AWSSpringBoot32LambdaWebAdapter"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\""
image_repositories = []
